# Generated by Django 5.2.5 on 2026-03-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0002_userworksheetclass_worksheet_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworksheetsemester',
            name='title',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
