# Generated by Django 5.2.5 on 2026-03-29 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0002_majorversionrequirements_choose_number'),
        ('worksheets', '0002_userworksheetclass_worksheet_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorksheetMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.majorversion')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.userworksheet')),
            ],
        ),
        migrations.CreateModel(
            name='UserWorksheetMajorFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.majorversionrequirements')),
                ('worksheet_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.userworksheetclass')),
                ('worksheet_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.userworksheetmajor')),
            ],
        ),
    ]
