# Generated by Django 5.2.5 on 2026-03-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0003_userworksheetsemester_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworksheetsemester',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
