# Generated by Django 5.2.5 on 2026-04-09 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0004_userworksheetsemester_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, default='', max_length=100)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_majors', to='worksheets.userworksheet')),
            ],
            options={
                'unique_together': {('worksheet', 'major_id', 'specialization')},
            },
        ),
    ]
