# Generated by Django 5.2.5 on 2026-02-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursetag_course_course_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_tag',
            new_name='course_tags',
        ),
    ]
