# Generated by Django 5.2.5 on 2026-04-08 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.PositiveIntegerField(blank=True, null=True)),
                ('language_requirement', models.CharField(blank=True, default='', max_length=10)),
                ('intended_major_id', models.CharField(blank=True, default='', max_length=100)),
                ('intended_language_code', models.CharField(blank=True, default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, default='', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_majors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'major_id')},
            },
        ),
    ]
